### PR TITLE
Fix MSVC compilation

### PR DESCRIPTION
**Pull request by glenfe**

### CODE REVIEW

**Comment by timblechmann** [comment]
@glenfe thanks a lot! especially for the appveyor integration. there's one build failure with msvc-12.0, i'm wondering if we might want to disable that configuration. any thoughts on this?

**Comment by glenfe** [comment]
@timblechmann Since it's just the forward declarations in mutable_heap_test.cpp that MSVC 12 has a problem with, I've suppressed those in the unit test. This way we still test MSVC 12 for all the other supported Heap features.

**Comment by timblechmann** [comment]
@glenfe great! i'll merge once the builds are green. thanks a lot!

**Comment by glenfe** [comment]
@timblechmann Thanks (all green now).

**Comment by glenfe** [comment]
Good to merge to master?

**Pull request merged**
